version: '3.9'

services:
    main:
        container_name: main
        build: 
            context: .
        env_file:
            - .env
        environment:
            - MONGODB_URI=mongodb://mongo_db:27017
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
            - 7457:7457
        command: npm run start:dev
        depends_on:
            - mongo_db
        restart: always

    mongo_db:
        container_name: mongo
        image: mongo:latest
        restart: always
        volumes:
            - mongo_db:/data/db

volumes:
    mongo_db: {}